name: claraflutter
description: Alles Klara Demo App for Lingo.dev Localization Automation.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true # Stops the warning
  uses-material-design: true
  assets:
    - lib/l10n/ # This allows reading the ARB files directly
